{
  "formatVersion": "1.1",
  "component": {
    "group": "com.orange.plugin",
    "module": "dependencies",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "dependencies-1.0.0.jar",
          "url": "dependencies-1.0.0.jar",
          "size": 4927,
          "sha512": "8e2438d110b8e774d33e4056156611cb6ba23db31b9c51af127c204f4cb5b1f4f700025aeff536929ce9affd2af6d5dbdeb1ef5fa0de5b9345be69d2c6eb5cfc",
          "sha256": "1265eb790c6c2a806712c9878805c287f2c1377cc4dfcb61d35d9cb890d39037",
          "sha1": "3836f6701cca727c11a1fef4df49190e591fbc8f",
          "md5": "d563125764740e28da8fe35b76a2f75c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "dependencies-1.0.0.jar",
          "url": "dependencies-1.0.0.jar",
          "size": 4927,
          "sha512": "8e2438d110b8e774d33e4056156611cb6ba23db31b9c51af127c204f4cb5b1f4f700025aeff536929ce9affd2af6d5dbdeb1ef5fa0de5b9345be69d2c6eb5cfc",
          "sha256": "1265eb790c6c2a806712c9878805c287f2c1377cc4dfcb61d35d9cb890d39037",
          "sha1": "3836f6701cca727c11a1fef4df49190e591fbc8f",
          "md5": "d563125764740e28da8fe35b76a2f75c"
        }
      ]
    }
  ]
}
